// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC82o7IAMlt01_wYhz7qIdDEVgtZTGKNVw',
    appId: '1:1086408132778:web:38397ce85afde9ae98a8d3',
    messagingSenderId: '1086408132778',
    projectId: 'fir-getx-e7de7',
    authDomain: 'fir-getx-e7de7.firebaseapp.com',
    storageBucket: 'fir-getx-e7de7.appspot.com',
    measurementId: 'G-M7YDGPYDPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT--oSGd6gSLZTqQX7s2ccBHFCP3c3iTk',
    appId: '1:1086408132778:android:c501aaec0a68d78f98a8d3',
    messagingSenderId: '1086408132778',
    projectId: 'fir-getx-e7de7',
    storageBucket: 'fir-getx-e7de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzPkFiJPr_LQtWwJiNcr0mfTkP4tZ0vWE',
    appId: '1:1086408132778:ios:6dc61a826d82f49398a8d3',
    messagingSenderId: '1086408132778',
    projectId: 'fir-getx-e7de7',
    storageBucket: 'fir-getx-e7de7.appspot.com',
    iosBundleId: 'com.example.firebasebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzPkFiJPr_LQtWwJiNcr0mfTkP4tZ0vWE',
    appId: '1:1086408132778:ios:a9dc2823de04fce898a8d3',
    messagingSenderId: '1086408132778',
    projectId: 'fir-getx-e7de7',
    storageBucket: 'fir-getx-e7de7.appspot.com',
    iosBundleId: 'com.example.firebasebase.RunnerTests',
  );
}
